// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtMyyLBdf3ZbGg4-9GAZ7xU4EZZbKAIiE',
    appId: '1:404504690912:web:298bf0ff77664ee4a2d085',
    messagingSenderId: '404504690912',
    projectId: 'mygarage-8c567',
    authDomain: 'mygarage-8c567.firebaseapp.com',
    storageBucket: 'mygarage-8c567.firebasestorage.app',
    measurementId: 'G-N17R8RGS90',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLYXVyBa7e5T6Ic-8tV_nJN09R7J-w4a8',
    appId: '1:404504690912:android:570a9993c13ed7eda2d085',
    messagingSenderId: '404504690912',
    projectId: 'mygarage-8c567',
    storageBucket: 'mygarage-8c567.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXnb400LD4pKvHAgJn65U3cyTAeSKDYPA',
    appId: '1:404504690912:ios:cd87a9bda965e988a2d085',
    messagingSenderId: '404504690912',
    projectId: 'mygarage-8c567',
    storageBucket: 'mygarage-8c567.firebasestorage.app',
    iosBundleId: 'com.example.mygarage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXnb400LD4pKvHAgJn65U3cyTAeSKDYPA',
    appId: '1:404504690912:ios:cd87a9bda965e988a2d085',
    messagingSenderId: '404504690912',
    projectId: 'mygarage-8c567',
    storageBucket: 'mygarage-8c567.firebasestorage.app',
    iosBundleId: 'com.example.mygarage',
  );
}
